"""
pytest conftest — shared fixtures.
"""

from __future__ import annotations

import pytest

from mrna_design.models.candidate import Candidate

# ── Well-known test sequences ─────────────────────────────────────────────────

EGFP_PROTEIN_SHORT = "MVSKGEELFTGVVPILVELDGDVNGHKFSVS"  # first 31 aa
EGFP_CDS_CAI_MAX = (
    "AUGGUUAGCAAGGGTGAGGAGCTGTTCACCGGTGTTGTCCCCATTCTGGTGGAGCTGGACGGTGACGTGAACGGTCACAAGTTCAGCGTGAGC"
)
# Note: above CDS is illustrative; real CDS is generated by the pipeline.


@pytest.fixture
def egfp_protein_short() -> str:
    return EGFP_PROTEIN_SHORT


@pytest.fixture
def minimal_candidate() -> Candidate:
    """A minimal 9-codon candidate for fast tests (no UTRs, no scoring)."""
    # Encodes: M V S K G E E L * (9 codons including stop)
    cds = "AUGGUUAGCAAAGGTGAGGAGCUG UAA".replace(" ", "")
    # Build a valid 9-codon CDS: MVSKGEEL* in RNA
    protein = "MVSKGEEL"
    cds = "AUGGUUUCGAAAGGTGAGGAGCUGUAA"
    return Candidate.from_cds(cds=cds, protein=protein, seed_strategy="test")


@pytest.fixture
def egfp_cds_candidate() -> Candidate:
    """A CAI-max seeded EGFP candidate (requires codon_table)."""
    from mrna_design.designer.seeds import seed_candidate

    protein = EGFP_PROTEIN_SHORT
    return seed_candidate(protein, strategy="cai_max")
